package com.example.ui.utils

object AppStrings {
    private val translations = mapOf(
        "id" to mapOf(
            "app_title" to "Globel - Hub Travel",
            "reset_hub" to "Reset Hub",
            "hello_user" to "Halo, {name}! 👋",
            "ready_to_takeoff" to "Siap lepas landas mencari teman baru hari ini?",
            "boarding_pass_title" to "BOARDING PASS VIRTUAL",
            "origin" to "Asal",
            "language" to "Bahasa Utama",
            "miles_travelled" to "JARAK TEMPUH",
            "miles_val" to "{miles} mil",
            "status" to "STATUS",
            "ready_to_fly" to "SIAP TERBANG 🟢",
            "matching_desc" to "Lepas landas dan mendarat di negara acak untuk mengobrol dengan penduduk lokal menggunakan terjemahan otomatis bertenaga AI Gemini!",
            "takeoff_btn" to "Mulai Lepas Landas 🚀",
            "recent_companions" to "Teman Perjalanan Anda (Chat Terbaru)",
            "no_companions" to "Belum ada teman perjalanan. Klik tombol 'Mulai Lepas Landas' di atas untuk mendarat di negara baru!",
            "bio_travel" to "Bio Perjalanan 📝",
            "edit_profile_title" to "Ubah Profil Saya",
            "edit_profile_desc" to "Sesuaikan paspor virtual perjalanan Anda",
            "save_changes" to "Simpan Perubahan",
            "cancel" to "Batal",
            "nickname" to "Nama Panggilan",
            "home_country" to "Negara Asal",
            "profile_pic" to "Foto Profil Perjalanan",
            "gallery_btn" to "Pilih Foto dari Galeri HP Anda 🖼️",
            "bio_title" to "Bio Perjalanan Anda",
            "bio_hint" to "Tulis petualangan Anda...",
            "error_name" to "Nama tidak boleh kosong!",
            "opening_route" to "Membuka Rute Udara...",
            "landed_safe" to "MENDARAT DENGAN SELAMAT! 🎉",
            "welcome_to" to "Selamat Datang di {city}!",
            "distance" to "JARAK TERBANG",
            "time_diff" to "BEDA WAKTU",
            "time_offset" to "UTC {offset} Jam",
            "start_chat_btn" to "Mulai Percakapan 💬",
            "back_to_hub" to "Kembali ke Hub",
            "icebreaker_greet" to "Kirim Salam Hangat 👋",
            "icebreaker_food" to "Tanya Makanan Khas 🍜",
            "icebreaker_weather" to "Tanya Cuaca di Sana ☀️",
            "icebreaker_places" to "Tanya Destinasi Keren 🗺️",
            "icebreaker_music" to "Kirim Rekomendasi Lagu 🎵",
            "back_desc" to "Kembali ke Hub",
            "send_message" to "Kirim pesan...",
            "typing" to "Sedang mengetik...",
            "original_msg" to "Asli: {msg}",
            "translated_msg" to "Terjemahan: {msg}",
            "nav_home" to "Beranda",
            "nav_companions" to "Teman Perjalanan"
        ),
        "en" to mapOf(
            "app_title" to "Globel - Travel Hub",
            "reset_hub" to "Reset Hub",
            "hello_user" to "Hello, {name}! 👋",
            "ready_to_takeoff" to "Ready to take off and find new friends today?",
            "boarding_pass_title" to "VIRTUAL BOARDING PASS",
            "origin" to "Origin",
            "language" to "Main Language",
            "miles_travelled" to "MILES TRAVELLED",
            "miles_val" to "{miles} miles",
            "status" to "STATUS",
            "ready_to_fly" to "READY TO FLY 🟢",
            "matching_desc" to "Take off and land in a random country to chat with locals using real-time AI Gemini automatic translation!",
            "takeoff_btn" to "Start Takeoff 🚀",
            "recent_companions" to "Your Travel Companions (Recent Chats)",
            "no_companions" to "No travel companions yet. Click the 'Start Takeoff' button above to land in a new country!",
            "bio_travel" to "Travel Bio 📝",
            "edit_profile_title" to "Edit My Profile",
            "edit_profile_desc" to "Customize your virtual travel passport",
            "save_changes" to "Save Changes",
            "cancel" to "Cancel",
            "nickname" to "Nickname",
            "home_country" to "Home Country",
            "profile_pic" to "Travel Profile Photo",
            "gallery_btn" to "Choose Photo from Gallery 🖼️",
            "bio_title" to "Your Travel Bio",
            "bio_hint" to "Write about your adventures...",
            "error_name" to "Name cannot be empty!",
            "opening_route" to "Opening Air Route...",
            "landed_safe" to "LANDED SAFELY! 🎉",
            "welcome_to" to "Welcome to {city}!",
            "distance" to "FLIGHT DISTANCE",
            "time_diff" to "TIME DIFFERENCE",
            "time_offset" to "UTC {offset} Hours",
            "start_chat_btn" to "Start Conversation 💬",
            "back_to_hub" to "Back to Hub",
            "icebreaker_greet" to "Send Warm Greeting 👋",
            "icebreaker_food" to "Ask About Local Food 🍜",
            "icebreaker_weather" to "Ask About Weather ☀️",
            "icebreaker_places" to "Ask About Cool Spots 🗺️",
            "icebreaker_music" to "Send Song Recommendation 🎵",
            "back_desc" to "Back to Hub",
            "send_message" to "Send a message...",
            "typing" to "Typing...",
            "original_msg" to "Original: {msg}",
            "translated_msg" to "Translated: {msg}",
            "nav_home" to "Home",
            "nav_companions" to "Companions"
        ),
        "ja" to mapOf(
            "app_title" to "Globel - トラベルハブ",
            "reset_hub" to "ハブをリセット",
            "hello_user" to "こんにちは、{name}さん！👋",
            "ready_to_takeoff" to "今日、新しい友達を見つけるために出発する準備はできていますか？",
            "boarding_pass_title" to "バーチャル搭乗券",
            "origin" to "出身国",
            "language" to "主な言語",
            "miles_travelled" to "旅行距離",
            "miles_val" to "{miles} マイル",
            "status" to "ステータス",
            "ready_to_fly" to "出発準備完了 🟢",
            "matching_desc" to "Gemini AIによるリアルタイム自動翻訳を使用して、ランダムな国に着陸し、現地の人々とチャットしましょう！",
            "takeoff_btn" to "出発する 🚀",
            "recent_companions" to "旅行仲間 (最近のチャット)",
            "no_companions" to "旅行仲間はまだいません。上の「出発する」ボタンをクリックして、新しい国に着陸しましょう！",
            "bio_travel" to "自己紹介 📝",
            "edit_profile_title" to "プロフィールの編集",
            "edit_profile_desc" to "バーチャル旅行パスポートをカスタマイズする",
            "save_changes" to "変更を保存",
            "cancel" to "キャンセル",
            "nickname" to "ニックネーム",
            "home_country" to "出身国",
            "profile_pic" to "プロフィール写真",
            "gallery_btn" to "ギャラリーから写真を選択 🖼️",
            "bio_title" to "自己紹介",
            "bio_hint" to "冒険について書く...",
            "error_name" to "名前を入力してください！",
            "opening_route" to "航空路を開設中...",
            "landed_safe" to "無事着陸しました！🎉",
            "welcome_to" to "{city}へようこそ！",
            "distance" to "飛行距離",
            "time_diff" to "時差",
            "time_offset" to "UTC {offset} 時間",
            "start_chat_btn" to "会話を開始 💬",
            "back_to_hub" to "ハブに戻る",
            "icebreaker_greet" to "暖かい挨拶を送る 👋",
            "icebreaker_food" to "郷土料理について尋ねる 🍜",
            "icebreaker_weather" to "天気について尋ねる ☀️",
            "icebreaker_places" to "おすすめの場所を尋ねる 🗺️",
            "icebreaker_music" to "おすすめ of 曲を送る 🎵",
            "back_desc" to "ハブに戻る",
            "send_message" to "メッセージを送信...",
            "typing" to "入力中...",
            "original_msg" to "原文: {msg}",
            "translated_msg" to "翻訳: {msg}",
            "nav_home" to "ホーム",
            "nav_companions" to "旅行仲間"
        ),
        "pt" to mapOf(
            "app_title" to "Globel - Hub de Viagem",
            "reset_hub" to "Redefinir Hub",
            "hello_user" to "Olá, {name}! 👋",
            "ready_to_takeoff" to "Pronto para decolar e encontrar novos amigos hoje?",
            "boarding_pass_title" to "CARTÃO DE EMBARQUE VIRTUAL",
            "origin" to "Origem",
            "language" to "Idioma Principal",
            "miles_travelled" to "MILHAS VIAJADAS",
            "miles_val" to "{miles} milhas",
            "status" to "STATUS",
            "ready_to_fly" to "PRONTO PARA VOAR 🟢",
            "matching_desc" to "Decole e pouse em um país aleatório para conversar com moradores locais usando tradução automática com tecnologia AI Gemini!",
            "takeoff_btn" to "Iniciar Decolagem 🚀",
            "recent_companions" to "Seus Companheiros de Viagem (Conversas)",
            "no_companions" to "Ainda não há companheiros de viagem. Clique no botão 'Iniciar Decolagem' acima para pousar em um novo país!",
            "bio_travel" to "Biografia de Viagem 📝",
            "edit_profile_title" to "Editar Meu Perfil",
            "edit_profile_desc" to "Personalize seu passaporte de viagem virtual",
            "save_changes" to "Salvar Alterações",
            "cancel" to "Cancelar",
            "nickname" to "Apelido",
            "home_country" to "País de Origem",
            "profile_pic" to "Foto do Perfil",
            "gallery_btn" to "Escolher Foto da Galeria 🖼️",
            "bio_title" to "Sua Biografia de Viagem",
            "bio_hint" to "Escreva sobre suas aventuras...",
            "error_name" to "O nome não pode ficar vazio!",
            "opening_route" to "Abrindo Rota Aérea...",
            "landed_safe" to "POUSOU COM SEGURANÇA! 🎉",
            "welcome_to" to "Bem-vindo a {city} !",
            "distance" to "DISTÂNCIA DE VOO",
            "time_diff" to "DIFERENÇA DE TEMPO",
            "time_offset" to "UTC {offset} Horas",
            "start_chat_btn" to "Iniciar Conversa 💬",
            "back_to_hub" to "Voltar para o Hub",
            "icebreaker_greet" to "Enviar Saudação 👋",
            "icebreaker_food" to "Perguntar sobre Comida Local 🍜",
            "icebreaker_weather" to "Perguntar sobre o Clima ☀️",
            "icebreaker_places" to "Perguntar sobre Lugares Legais 🗺️",
            "icebreaker_music" to "Enviar Recomendação de Música 🎵",
            "back_desc" to "Voltar para o Hub",
            "send_message" to "Enviar mensagem...",
            "typing" to "Digitando...",
            "original_msg" to "Original: {msg}",
            "translated_msg" to "Traduzido: {msg}",
            "nav_home" to "Início",
            "nav_companions" to "Companheiros"
        ),
        "fr" to mapOf(
            "app_title" to "Globel - Hub de Voyage",
            "reset_hub" to "Réinitialiser le Hub",
            "hello_user" to "Bonjour, {name} ! 👋",
            "ready_to_takeoff" to "Prêt à décoller et à trouver de nouveaux amis aujourd'hui ?",
            "boarding_pass_title" to "CARTE D'EMBARQUEMENT VIRTUELLE",
            "origin" to "Origine",
            "language" to "Langue principale",
            "miles_travelled" to "MILLES PARCOURUS",
            "miles_val" to "{miles} milles",
            "status" to "STATUT",
            "ready_to_fly" to "PRÊT À VOLER 🟢",
            "matching_desc" to "Décollez et atterrissez dans un pays aléatoire pour discuter avec des locaux grâce à la traduction automatique par l'IA Gemini !",
            "takeoff_btn" to "Démarrer le Décollage 🚀",
            "recent_companions" to "Vos compagnons de voyage (Chats récents)",
            "no_companions" to "Pas encore de compagnon de voyage. Cliquez sur le bouton 'Démarrer le Décollage' ci-dessus pour atterrir dans un nouveau pays !",
            "bio_travel" to "Bio de voyage 📝",
            "edit_profile_title" to "Modifier mon profil",
            "edit_profile_desc" to "Personnalisez votre passeport de voyage virtuel",
            "save_changes" to "Sauvegarder",
            "cancel" to "Annuler",
            "nickname" to "Surnom",
            "home_country" to "Pays d'origine",
            "profile_pic" to "Photo de profil",
            "gallery_btn" to "Choisir de la galerie 🖼️",
            "bio_title" to "Votre bio de voyage",
            "bio_hint" to "Écrivez sur vos aventures...",
            "error_name" to "Le nom ne peut pas être vide !",
            "opening_route" to "Ouverture de la route aérienne...",
            "landed_safe" to "ATTERRI EN TOUTE SÉCURITÉ ! 🎉",
            "welcome_to" to "Bienvenue à {city} !",
            "distance" to "DISTANCE DE VOL",
            "time_diff" to "DIFFÉRENCE HEURE",
            "time_offset" to "UTC {offset} Heures",
            "start_chat_btn" to "Commencer la discussion 💬",
            "back_to_hub" to "Retour au Hub",
            "icebreaker_greet" to "Envoyer un message amical 👋",
            "icebreaker_food" to "Demander sur la nourriture locale 🍜",
            "icebreaker_weather" to "Demander sur la météo ☀️",
            "icebreaker_places" to "Demander sur les coins sympas 🗺️",
            "icebreaker_music" to "Envoyer une recommandation de chanson 🎵",
            "back_desc" to "Retour au Hub",
            "send_message" to "Envoyer un message...",
            "typing" to "Écrit...",
            "original_msg" to "Original : {msg}",
            "translated_msg" to "Traduction : {msg}",
            "nav_home" to "Accueil",
            "nav_companions" to "Compagnons"
        ),
        "ar" to mapOf(
            "app_title" to "Globel - محور السفر",
            "reset_hub" to "إعادة تعيين المحور",
            "hello_user" to "مرحباً، {name}! 👋",
            "ready_to_takeoff" to "هل أنت مستعد للانطلاق والعثور على أصدقاء جدد اليوم؟",
            "boarding_pass_title" to "بطاقة صعود افتراضية",
            "origin" to "الأصل",
            "language" to "اللغة الرئيسية",
            "miles_travelled" to "المسافة المقطوعة",
            "miles_val" to "{miles} ميل",
            "status" to "الحالة",
            "ready_to_fly" to "جاهز للطيران 🟢",
            "matching_desc" to "انطلق واهبط في بلد عشوائي للدردشة مع السكان المحليين باستخدام الترجمة التلقائية المدعومة بـ Gemini AI!",
            "takeoff_btn" to "بدء الإقلاع 🚀",
            "recent_companions" to "رفاق سفرك (المحادثات الأخيرة)",
            "no_companions" to "لا يوجد رفاق سفر بعد. انقر على زر 'بدء الإقلاع' أعلاه للهبوط في بلد جديد!",
            "bio_travel" to "نبذة عن السفر 📝",
            "edit_profile_title" to "تعديل الملف الشخصي",
            "edit_profile_desc" to "تخصيص جواز سفرك الافتراضي",
            "save_changes" to "حفظ التغييرات",
            "cancel" to "إلغاء",
            "nickname" to "الاسم المستعار",
            "home_country" to "البلد الأصلي",
            "profile_pic" to "صورة الملف الشخصي",
            "gallery_btn" to "اختر صورة من المعرض 🖼️",
            "bio_title" to "نبذة سفرك",
            "bio_hint" to "اكتب عن مغامراتك...",
            "error_name" to "لا يمكن أن يكون الاسم فارغاً!",
            "opening_route" to "فتح المسار الجوي...",
            "landed_safe" to "هبطت بأمان! 🎉",
            "welcome_to" to "مرحباً بك في {city}!",
            "distance" to "مسافة الرحلة",
            "time_diff" to "فارق التوقيت",
            "time_offset" to "UTC {offset} ساعات",
            "start_chat_btn" to "بدء المحادثة 💬",
            "back_to_hub" to "العودة للمحور",
            "icebreaker_greet" to "إرسال تحية دافئة 👋",
            "icebreaker_food" to "السؤال عن الأكل المحلي 🍜",
            "icebreaker_weather" to "السؤال عن الطقس ☀️",
            "icebreaker_places" to "السؤال عن الأماكن الرائعة 🗺️",
            "icebreaker_music" to "إرسال توصية بأغنية 🎵",
            "back_desc" to "العودة للمحور",
            "send_message" to "إرسال رسالة...",
            "typing" to "يكتب الآن...",
            "original_msg" to "الأصل: {msg}",
            "translated_msg" to "الترجمة: {msg}",
            "nav_home" to "الرئيسية",
            "nav_companions" to "الرفقاء"
        ),
        "de" to mapOf(
            "app_title" to "Globel - Reise-Hub",
            "reset_hub" to "Hub zurücksetzen",
            "hello_user" to "Hallo, {name}! 👋",
            "ready_to_takeoff" to "Bereit abzuheben und heute neue Freunde zu finden?",
            "boarding_pass_title" to "VIRTUELLE BORDKARTE",
            "origin" to "Herkunft",
            "language" to "Hauptsprache",
            "miles_travelled" to "REISEMEILEN",
            "miles_val" to "{miles} Meilen",
            "status" to "STATUS",
            "ready_to_fly" to "ABFLUGBEREIT 🟢",
            "matching_desc" to "Heben Sie ab und landen Sie in einem zufälligen Land, um mit Einheimischen über die KI-gestützte automatische Übersetzung von Gemini zu chatten!",
            "takeoff_btn" to "Starten 🚀",
            "recent_companions" to "Ihre Reisebegleiter (Letzte Chats)",
            "no_companions" to "Noch keine Reisebegleiter. Klicken Sie oben auf 'Starten', um in einem neuen Land zu landen!",
            "bio_travel" to "Reise-Bio 📝",
            "edit_profile_title" to "Profil bearbeiten",
            "edit_profile_desc" to "Virtuellen Reisepass anpassen",
            "save_changes" to "Änderungen speichern",
            "cancel" to "Abbrechen",
            "nickname" to "Spitzname",
            "home_country" to "Heimatland",
            "profile_pic" to "Profilbild",
            "gallery_btn" to "Foto aus Galerie auswählen 🖼️",
            "bio_title" to "Ihre Reise-Bio",
            "bio_hint" to "Schreiben Sie über Ihre Abenteuer...",
            "error_name" to "Name darf nicht leer sein!",
            "opening_route" to "Flugroute wird geöffnet...",
            "landed_safe" to "SICHER GELANDET! 🎉",
            "welcome_to" to "Willkommen in {city}!",
            "distance" to "FLUGDISTANZ",
            "time_diff" to "ZEITUNTERSCHIED",
            "time_offset" to "UTC {offset} Stunden",
            "start_chat_btn" to "Konversation starten 💬",
            "back_to_hub" to "Zurück zum Hub",
            "icebreaker_greet" to "Herzlichen Gruß senden 👋",
            "icebreaker_food" to "Nach lokalem Essen fragen 🍜",
            "icebreaker_weather" to "Nach dem Wetter fragen ☀️",
            "icebreaker_places" to "Nach coolen Orten fragen 🗺️",
            "icebreaker_music" to "Liedempfehlung senden 🎵",
            "back_desc" to "Zurück zum Hub",
            "send_message" to "Nachricht senden...",
            "typing" to "Schreibt...",
            "original_msg" to "Original: {msg}",
            "translated_msg" to "Übersetzt: {msg}",
            "nav_home" to "Startseite",
            "nav_companions" to "Begleiter"
        )
    )

    fun get(key: String, langCode: String): String {
        val normalizedCode = langCode.lowercase()
        val langMap = translations[normalizedCode] ?: translations["id"]!!
        return langMap[key] ?: translations["id"]!![key] ?: key
    }

    fun get(key: String, langCode: String, vararg args: Pair<String, String>): String {
        var str = get(key, langCode)
        for (arg in args) {
            str = str.replace("{${arg.first}}", arg.second)
        }
        return str
    }
}
